import { PrismaClient } from "@prisma/client";

export async function seedProducts(db: PrismaClient) {
  const cocktailCategory = await db.category.upsert({
    where: { name: "Cocktails" },
    update: {},
    create: {
      name: "Cocktails",
    },
  });

  const refillCategory = await db.category.upsert({
    where: { name: "Refills" },
    update: {},
    create: {
      name: "Refills",
    },
  });

  const products = [
    {
      productId: 1,
      name: "Margarita",
      description: "A delicious and refreshing cocktail",
      ingredients: "Tequila, lime juice, triple sec",
      image: "/Margarita.jpg",
      slug: "margarita",
      price: 10.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 2,
      name: "Mojito",
      description: "A refreshing minty cocktail",
      ingredients: "White rum, lime juice, mint leaves",
      image: "/mojito.jpg",
      slug: "mojito",
      price: 9.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 3,
      name: "Pornstar Martini",
      description: "A fruity and sweet cocktail",
      ingredients: "Vanilla vodka, passion fruit, lime juice",
      image: "/pornstar-martini.jpg",
      slug: "pornstar-martini",
      price: 12.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 4,
      name: "Tequila Sunrise",
      description: "A bottle of tequila",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/tequila-sunrise.jpg",
      slug: "tequila-sunrise",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    ,
    {
      productId: 5,
      name: "Paloma",
      description: "A bottle of tequila",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/paloma.jpg",
      slug: "paloma",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 6,
      name: "Espresso Martini",
      description: "A bottle of tequila",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/espresso-martini.jpg",
      slug: "espresso-martini",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 7,
      name: "Tom Collins",
      description: "A bottle of tequila",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/tom-collins.jpg",
      slug: "tom-collins",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    {
      productId: 8,
      name: "Old Fashioned",
      description: "A bottle of tequila",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/old-fashioned.jpg",
      slug: "old-fashioned",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: cocktailCategory.id,
      caseColors: ["#51A638", "#ffd93c", "#F149B3", "#147AB5"],
      subColors: ["#81EE42", "#fffa7d", "#FAE5EB", "#C6F3FA"],
      caseImages: [
        "/green-case.jpg",
        "/yellow-case.jpg",
        "/pink-case.jpg",
        "/blue-case.jpg",
      ],
    },
    // Refills
    {
      productId: 9,
      name: "Margarita Refill",
      description: "A fizzy refill of margarita",
      ingredients: "Tequila, lime juice, triple sec",
      image: "/refill-case.png",
      slug: "margarita-refill",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: refillCategory.id,
      caseColors: [],
      subColors: [],
      caseImages: [],
    },
    {
      productId: 10,
      name: "Mojito Refill",
      description: "A fizzy refill of mojito",
      ingredients: "White rum, lime juice, mint leaves",
      image: "/refill-case.png",
      slug: "mojito-refill",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: refillCategory.id,
      subColors: [],
      caseColors: [],
      caseImages: [],
    },
    {
      productId: 11,
      name: "Pornstar Martini Refill",
      description: "A fizzy refill of pornstar martini",
      ingredients: "Vanilla vodka, passion fruit, lime juice",
      image: "/refill-case.png",
      slug: "pornstar-martini-refill",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: refillCategory.id,
      subColors: [],
      caseColors: [],
      caseImages: [],
    },
    {
      productId: 12,
      name: "Tequila Sunrise Refill",
      description: "A fizzy refill of tequila sunrise",
      ingredients: "Tequila, orange juice, grenadine",
      image: "/refill-case.png",
      slug: "tequila-sunrise-refill",
      price: 29.99,
      alcohol: 12.5,
      tabletQuantity: 18,
      isBestSeller: true,
      categoryId: refillCategory.id,
      subColors: [],
      caseColors: [],
      caseImages: [],
    },
  ];

  // Iterera över produkterna och skapa/uppdatera dem i databasen
  for (const product of products) {
    if (!product) continue;

    await db.product.upsert({
      where: { productId: product.productId },
      update: {},
      create: {
        productId: product.productId,
        name: product.name,
        description: product.description,
        ingredients: product.ingredients,
        image: product.image,
        slug: product.slug,
        price: product.price,
        alcohol: product.alcohol,
        tabletQuantity: product.tabletQuantity,
        isBestSeller: product.isBestSeller,
        caseColors: product.caseColors,
        subColors: product.subColors,
        categories: { connect: { id: product.categoryId } },
        caseImages: product.caseImages,
      },
    });
  }
}
